### ISSUE TITLE
Reasoning for needing browser history?

### ISSUE THREAD

**Issue by ImDini** [mstfsnc/twitter-video-downloader-extension#16]
Staying away from this extension forever now regardless of answer, just curious. Why would a twitter only extension need to read any sort of browsing history?

**Comment by mstfsnc** [comment]
Hi @ImDini,

I made a development that [reloads the tabs after installed](https://github.com/mstfsnc/twitter-video-downloader-extension/blob/master/src/background/index.js#L41-L50) so extension can work more stable in [version 2.0.1](https://github.com/mstfsnc/twitter-video-downloader-extension/commit/1d24410f29d17d8d8e1c29403bc7cf7924b3ef18). I thought needes the "tabs" permission. But I guess the "tabs" permission is a access contains browser history functions. For this reason, when before installing the extension, it issued a warning to users that it can read their browser history. I did some research on this issue after reading your previous comment to extension. I immediately removed the "tabs" permission in [version 2.0.2](https://github.com/mstfsnc/twitter-video-downloader-extension/commit/d9cdbc5503ebcdf6e71d6fe23cd11f3588ad0bc9) when I found out that [other developers were having this problem as well](https://stackoverflow.com/questions/64063754/chrome-extension-tabs-permissions-shows-read-your-browsing-history).

I don't have any malicious intent to read browser history or otherwise. I'm developing the extension as open source so people can see all the improvements I've made. If there is a malicious development, the developers can detect it when they examine the code.

Sorry if I couldn't answer your question. I translated it because my English is not very good.
